### ISSUE TITLE
game crashed

### ISSUE THREAD

**Issue by Microsoft6477** [Harleyoc1/DynamicTreesHeatAndClimate#1]
Game crashed while loading a world
Mod Version: 1.12.2-2.0.0
Dynamic trees version: 0.9.21
HeatAndClimate version: 3.4.3
HeatAndClimateLib version: 3.4.2

crash report("Use Heat and Climate Seasons"=true)
java.lang.AbstractMethodError: com.harleyoconnor.dynamictreeshnc.seasons.SeasonProviderHeatAndClimate.getSeasonValue(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Ljava/lang/Float;
    at com.ferreusveritas.dynamictrees.seasons.SeasonContext.updateTick(SeasonContext.java:31)
    at com.ferreusveritas.dynamictrees.seasons.SeasonManager.updateTick(SeasonManager.java:73)
    at com.ferreusveritas.dynamictrees.seasons.SeasonHelper.updateTick(SeasonHelper.java:33)
    at com.ferreusveritas.dynamictrees.event.CommonEventHandler.onWorldTick(CommonEventHandler.java:26)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2221_CommonEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:752)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
**==========================================================================**
crash report("Use Heat and Climate Seasons"=false)
java.lang.NoSuchMethodError: com.ferreusveritas.dynamictrees.seasons.SeasonHelper.getSeasonValue(Lnet/minecraft/world/World;)Ljava/lang/Float;
    at com.harleyoconnor.dynamictreeshnc.genfeatures.FeatureGenFruitLeaves.attemptLeafChange(FeatureGenFruitLeaves.java:57)
    at com.harleyoconnor.dynamictreeshnc.genfeatures.FeatureGenFruitLeaves.changeLeaves(FeatureGenFruitLeaves.java:102)
    at com.harleyoconnor.dynamictreeshnc.genfeatures.FeatureGenFruitLeaves.postGeneration(FeatureGenFruitLeaves.java:49)
    at com.ferreusveritas.dynamictrees.trees.Species.postGeneration(Species.java:1388)
    at com.ferreusveritas.dynamictrees.worldgen.JoCode.generate(JoCode.java:245)
    at com.ferreusveritas.dynamictrees.trees.Species.generate(Species.java:1291)
    at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.makeTree(TreeGenerator.java:161)
    at com.ferreusveritas.dynamictrees.worldgen.WorldGeneratorTrees.lambda$generate$1(WorldGeneratorTrees.java:143)
    at java.util.ArrayList.forEach(ArrayList.java:1259)
    at com.ferreusveritas.dynamictrees.worldgen.WorldGeneratorTrees.generate(WorldGeneratorTrees.java:143)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at micdoodle8.mods.galacticraft.core.TransformerHooks.otherModGenerate(TransformerHooks.java:198)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:980)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.tick(PlayerChunkMap.java:226)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

**Comment by jev217** [comment]
Getting same error.

**Comment by supermassimo** [comment]
will take a look

**Comment by supermassimo** [comment]
Fixed in [2.0.1](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-heat-and-climate/files/3121957)
