### ISSUE TITLE
Crash again but different from previous version

### ISSUE THREAD

**Issue by Microsoft6477** [Harleyoc1/DynamicTreesHeatAndClimate#2]
mod version: DynamicTreesHNC-1.12.2-2.0.1
forge version: 14.23.5.2854(latest)
mods list:
DynamicTrees-1.12.2-0.9.21
DynamicTreesHNC-1.12.2-2.0.1
HeatAndClimateLib_1.12.2-3.4.2
HeatAndClimateMod_1.12.2-3.4.3

when "Use Heat and Climate Seasons"=true
game crashed while loading a world
when "Use Heat and Climate Seasons"=false
game crashed while exploring a world

crash reports:
**when "Use Heat and Climate Seasons"=true**
java.lang.AbstractMethodError: com.harleyoconnor.dynamictreeshnc.seasons.SeasonProviderHeatAndClimate.getSeasonValue(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)Ljava/lang/Float;
	at com.ferreusveritas.dynamictrees.seasons.SeasonContext.updateTick(SeasonContext.java:31)
	at com.ferreusveritas.dynamictrees.seasons.SeasonManager.updateTick(SeasonManager.java:73)
	at com.ferreusveritas.dynamictrees.seasons.SeasonHelper.updateTick(SeasonHelper.java:33)
	at com.ferreusveritas.dynamictrees.event.CommonEventHandler.onWorldTick(CommonEventHandler.java:26)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_CommonEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

===============================================
**when "Use Heat and Climate Seasons"=false**
java.lang.NoSuchMethodError: com.ferreusveritas.dynamictrees.seasons.SeasonHelper.getSeasonValue(Lnet/minecraft/world/World;)Ljava/lang/Float;
	at com.harleyoconnor.dynamictreeshnc.genfeatures.FeatureGenFruitLeaves.getSeasonValue(FeatureGenFruitLeaves.java:54)
	at com.harleyoconnor.dynamictreeshnc.genfeatures.FeatureGenFruitLeaves.attemptLeafChange(FeatureGenFruitLeaves.java:63)
	at com.harleyoconnor.dynamictreeshnc.genfeatures.FeatureGenFruitLeaves.changeLeaves(FeatureGenFruitLeaves.java:108)
	at com.harleyoconnor.dynamictreeshnc.genfeatures.FeatureGenFruitLeaves.postGeneration(FeatureGenFruitLeaves.java:49)
	at com.ferreusveritas.dynamictrees.trees.Species.postGeneration(Species.java:1388)
	at com.ferreusveritas.dynamictrees.worldgen.JoCode.generate(JoCode.java:245)
	at com.ferreusveritas.dynamictrees.trees.Species.generate(Species.java:1291)
	at com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.makeTree(TreeGenerator.java:161)
	at com.ferreusveritas.dynamictrees.worldgen.WorldGeneratorTrees.lambda$generate$1(WorldGeneratorTrees.java:143)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.ferreusveritas.dynamictrees.worldgen.WorldGeneratorTrees.generate(WorldGeneratorTrees.java:143)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by supermassimo** [comment]
Fixed in [2.0.2](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-heat-and-climate/files/3272028)
